# Generated by Django 2.2.3 on 2019-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='assets/webs/images'),
        ),
    ]
